### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by shaneoreilly** [MikeDabrowski/franz-themed-recipes#3]
I can't get this to work on the mac version. 
Any ideas?

**Comment by MikeDabrowski** [comment]
I don't have any mac to check it out. Where did you put the files from this repo and do you use my fork of franz ?

**Comment by larsenwork** [comment]
@MikeDabrowski I just tried out mac too and couldn't get it to work. Recipes on mac is located in `~/Library/Application Support/Franz/` 

I clone, rename folders, launch Franz and get greeted by a "You have no services" screen. If I try to add a service (e.g. messenger) nothing happens when I click the icon on the ad service screen.

**Comment by MikeDabrowski** [comment]
Do you use my fork of Franz?

**Comment by larsenwork** [comment]
@MikeDabrowski that I did not, didn't see that anywhere in the readme, but I'll try that out later today 👍

**Comment by MikeDabrowski** [comment]
You are right to point that missing in the readme. I didn't test original Franz with themed recipes. It should look the same. It's my fork that adds functionality to switch themes in themed recipes. 
What worries me here is that 'can't add recipe' bug. I'll try to find some time to address it.

**Comment by MikeDabrowski** [comment]
If you clone this repo to recipes dir and use regular Franz it will fail when reading recipes. The reason for this is that original Franz tries to read every directory inside recipes directory and git places its stuff inside `.git` folder, which Franz can't read or parse. 

I fixed it some time ago in my fork so in order to use themed recipes now (when you encountered that problem) just uninstall Franz and install mine fork. 

I can't provide mac installer so you have to build it yourself. Clone my franz fork, then install dependencies and run build. After that installer should be in `out` directory. 
When recipes aren't working after you've installed my fork, try `git reset --hard origin/master` in recipes folder and reload / restart Franz. Let me know how it worked.

**Comment by MikeDabrowski** [comment]
Is this issue resolved now ?

**Comment by larsenwork** [comment]
@MikeDabrowski Sorry, I would assume so. I switched office position the day after so I'm now sitting next to a sunny window and therefore I had to switch to non-Darkmode for all things :) 

You can close this for now and reopen should anyone else have the issue. I see you updated the readme 👍 https://github.com/MikeDabrowski/franz-themed-recipes/commit/4c637a24b99c0dee5ce7a48e9d8de8386c9634e3

**Comment by dhawaljoh** [comment]
Can confirm I used your fork @MikeDabrowski and followed the instructions. Same problem as @larsenwork.

**Comment by MikeDabrowski** [comment]
@dhawaljoh Try Ferdi fork. It is way superior

**Comment by dhawaljoh** [comment]
Ha, I left Ferdi to come find you. My Ferdi keeps refreshing and doesn't feel as clean as Franz :/
